### ISSUE TITLE
[bug] extension breaked non-web3 website

### ISSUE THREAD

**Issue by imtipi** [blocksecteam/metasuites#24]
example link: https://www.elitepvpers.com/forum/diablo-4-trading/5144143-d4-season-3-leveling-1-100-dungeon-carry-gear-full-builds-starter-pack.html

extension enabled:
![image](https://github.com/blocksecteam/metasuites/assets/27230181/7c9877b9-98c7-47ce-aa9a-3ff7bb2f6a49)

extension disabled:
![image](https://github.com/blocksecteam/metasuites/assets/27230181/78db050e-348a-4b00-8ede-94442c6ec453)

better keep extension allow site access as whitelist...

**Comment by cong1223** [comment]
Thank you for reporting the bug. We will work quickly to reproduce and fix it.

**Comment by cong1223** [comment]
Thank you for your feedback. MetaSuites has resolved this issue in version 4.8.0, and it has now been published.
