### ISSUE TITLE
Error with Arkham custom labels 

### ISSUE THREAD

**Issue by zknpr** [blocksecteam/metasuites#26]
Hi, trying the new 5.0.0 update, I find that there is a bug when you save a private custom label from an address that you have already labeled on Arkham, the error seems to be that: metadock save the custom label instead of the address.

**Comment by 0xbe37e** [comment]
Thank you for the report. We'll work to reproduce and fix it promptly.

**Comment by zknpr** [comment]
Thanks, I actually found another 2 bugs with private custom labels, don't know if the problem is only mine, I'm using brave browser if this info can help.

1) Can't import my private custom labels, the extension prompt the "imported success" message but doesn't import the labels 

2) [EVM] when i have saved a custom label, the "to" section of the tx page changes with the last custom labels i have saved for all txs (i tried this with basescan and arbiscan)

Video of the 2nd bug
https://github.com/blocksecteam/metasuites/assets/96851588/c2e62188-cf40-469d-99e8-adff782820f5

**Comment by 0xbe37e** [comment]
The first issue has already been fixed in version 5.0.1, and we will fix the second issue as soon as possible.

**Comment by zknpr** [comment]
Thank you.

**Comment by 0xbe37e** [comment]
Thank you for your feedback. Version 5.0.2 will fix all of the above issues, and it will be released in the next few days.
