### ISSUE TITLE
add recent etherscan-based block explorers

### ISSUE THREAD

**Issue by Philx0** [blocksecteam/metasuites#32]
Please add recent etherscan-based block explorers such as mantlescan and blastscan.
see [https://etherscan.io/eaas](https://etherscan.io/eaas).

**Comment by cong1223** [comment]
Thank you for your suggestion. We will complete the adaptation for MantleScan in the near future, and we may prioritize other chains as well.

**Comment by cong1223** [comment]
The version compatible with MantleScan has been released.
