### ISSUE TITLE
Feature request.  Add custom address lable/nickname

### ISSUE THREAD

**Issue by lxhyl** [blocksecteam/metasuites#9]
**scan have add label function. But is hard to use. User must login and data storage in server not local.

Can we add this feature?

**Comment by cong1223** [comment]
Thank you for your suggestion! This feature is already on the roadmap, so stay tuned for more updates.

**Comment by lxhyl** [comment]
Thanks for you work. Is there anything I can do to help?

**Comment by 0xbe37e** [comment]
We've completed the feature you requested. The new functionality is available in version 5.x. Let me know if you have any questions.
Thank you for the feedback.

**Comment by lxhyl** [comment]
Thank you so much for your hard work in implementing the feature. I truly appreciate your dedication and effort!
